/* eslint-disable */
/**
 * Generated by convex codegen — stub for convex-test compatibility.
 *
 * THIS FILE IS AUTO-GENERATED AND SHOULD NOT BE EDITED MANUALLY.
 */

import { anyApi, componentsGeneric } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
