/* eslint-disable */
/**
 * Generated by convex codegen — stub for convex-test compatibility.
 *
 * THIS FILE IS AUTO-GENERATED AND SHOULD NOT BE EDITED MANUALLY.
 */

import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

/**
 * Define a query in this Convex app's public API.
 */
export const query = queryGeneric;

/**
 * Define a query that is only callable from other Convex functions.
 */
export const internalQuery = internalQueryGeneric;

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = mutationGeneric;

/**
 * Define a mutation that is only callable from other Convex functions.
 */
export const internalMutation = internalMutationGeneric;

/**
 * Define an action in this Convex app's public API.
 */
export const action = actionGeneric;

/**
 * Define an action that is only callable from other Convex functions.
 */
export const internalAction = internalActionGeneric;

/**
 * Define an HTTP action.
 */
export const httpAction = httpActionGeneric;
