import type { Dirent } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  collectRemoteManifest,
  renderGeneratedFile,
  toModuleId,
  type GeneratedRemoteManifest,
  type RegistryEntry,
} from "@/manifest";

import { stripRemoteOnlyExports, type StripResult } from "./strip";

export interface RunCodegenInput {
  convexDir: string;
  outFile: string;
  cwd?: string;
}

export interface RunCodegenResult {
  outFile: string;
  modulesIncluded: string[];
  modulesStripped: string[];
  modulesExcluded: string[];
  companionFiles: string[];
}

const STRIPPED_DIR = "_generated/embedded";

export async function runCodegen(
  input: RunCodegenInput,
): Promise<RunCodegenResult> {
  const cwd = input.cwd ?? process.cwd();
  const convexRoot = path.resolve(cwd, input.convexDir);
  const outFile = path.resolve(cwd, input.outFile);
  const strippedDir = path.resolve(convexRoot, STRIPPED_DIR);

  const allFiles = (await listTsFiles(convexRoot)).filter(
    (filePath) =>
      path.resolve(filePath) !== outFile &&
      !filePath.startsWith(strippedDir + path.sep),
  );

  const manifest: GeneratedRemoteManifest = {
    routeModes: {},
    tables: {},
  };

  const includedFiles: string[] = [];
  const strippedFiles: { original: string; companion: string }[] = [];
  const excludedModuleIds: string[] = [];

  for (const filePath of allFiles) {
    const source = await readFile(filePath, "utf8");
    const moduleId = toModuleId(convexRoot, filePath);

    const remote = await collectRemoteManifest({
      convexRoot,
      moduleId,
      source,
    });
    Object.assign(manifest.routeModes, remote.routeModes);
    Object.assign(manifest.tables, remote.tables);
    manifest.uploadUrl ??= remote.uploadUrl;

    const stripped = stripRemoteOnlyExports({ source, fileName: filePath });

    if (stripped.removedExports.length === 0) {
      includedFiles.push(filePath);
      continue;
    }

    if (!stripped.hasAnyExports) {
      excludedModuleIds.push(moduleId);
      continue;
    }

    const relativeToConvex = path.relative(convexRoot, filePath);
    const companionPath = path.join(strippedDir, relativeToConvex);
    await mkdir(path.dirname(companionPath), { recursive: true });
    await writeFile(companionPath, withGeneratedHeader(stripped), "utf8");
    strippedFiles.push({ original: filePath, companion: companionPath });
  }

  const moduleFiles: RegistryEntry[] = [
    ...includedFiles.map((file) => ({ originalFile: file, importFile: file })),
    ...strippedFiles.map((entry) => ({
      originalFile: entry.original,
      importFile: entry.companion,
    })),
  ];

  await mkdir(path.dirname(outFile), { recursive: true });
  await writeFile(
    outFile,
    renderGeneratedFile({
      outFile,
      moduleFiles,
      convexDir: convexRoot,
      manifest,
    }),
    "utf8",
  );

  return {
    outFile,
    modulesIncluded: includedFiles.map((f) => toModuleId(convexRoot, f)),
    modulesStripped: strippedFiles.map((s) =>
      toModuleId(convexRoot, s.original),
    ),
    modulesExcluded: excludedModuleIds,
    companionFiles: strippedFiles.map((s) => s.companion),
  };
}

function withGeneratedHeader(stripped: StripResult): string {
  const removed = stripped.removedExports.length;
  const noun = removed === 1 ? "export" : "exports";
  return `// AUTO-GENERATED by @robelest/convex-embedded codegen — DO NOT EDIT
// ${removed} remoteOnly ${noun} stripped from this companion module.
// Edit the original module under convex/ instead; this file is regenerated.

${stripped.source.replace(/^\s+/, "")}`;
}

async function listTsFiles(root: string): Promise<string[]> {
  let entries: Dirent[];
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch {
    return [];
  }
  const files = await Promise.all(
    entries.map(async (entry) => {
      const next = path.join(root, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "_generated") {
          return [] as string[];
        }
        return listTsFiles(next);
      }
      if (!entry.isFile()) return [] as string[];
      if (!/\.(ts|tsx|mts|cts)$/.test(entry.name)) return [] as string[];
      if (entry.name.endsWith(".d.ts")) return [] as string[];
      return [next];
    }),
  );
  return files.flat().sort();
}
